version: '3'

volumes:
  pg_data:
  static:
  media:

services:

  postgres:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./backend/
    image: kittygram_backend
    env_file: .env
    volumes:
      - static:/app/static/.
      - media:/app/media/.
    depends_on:
      - postgres  

  frontend:
    build: ./frontend/
    image: kittygram_frontend
    volumes:
      - static:/app/build/.

  gateway:
    build: ./nginx
    image: kittygram_gateway
    volumes:
      - static:/static/
      - media:/media/
    depends_on:
      - frontend
      - backend
    ports:
      - 80:80
    